// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC41QScxL2QIrEOKFHu42-VTnmflW7ZLzI',
    appId: '1:520142220218:web:3a7e600278319319590b83',
    messagingSenderId: '520142220218',
    projectId: 'ones-3f249',
    authDomain: 'ones-3f249.firebaseapp.com',
    databaseURL: 'https://ones-3f249-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ones-3f249.firebasestorage.app',
    measurementId: 'G-3XX4WPD346',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtEsizlXwFSOtaWGb_Bm0iZ_KpGKKbLC4',
    appId: '1:520142220218:android:f998a70f990176a7590b83',
    messagingSenderId: '520142220218',
    projectId: 'ones-3f249',
    databaseURL: 'https://ones-3f249-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ones-3f249.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_U8TQCJCgV_6zA_wo3wbsBkT-iOtCxk4',
    appId: '1:520142220218:ios:db831294acfde821590b83',
    messagingSenderId: '520142220218',
    projectId: 'ones-3f249',
    databaseURL: 'https://ones-3f249-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ones-3f249.firebasestorage.app',
    iosBundleId: 'com.example.last',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_U8TQCJCgV_6zA_wo3wbsBkT-iOtCxk4',
    appId: '1:520142220218:ios:db831294acfde821590b83',
    messagingSenderId: '520142220218',
    projectId: 'ones-3f249',
    databaseURL: 'https://ones-3f249-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ones-3f249.firebasestorage.app',
    iosBundleId: 'com.example.last',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC41QScxL2QIrEOKFHu42-VTnmflW7ZLzI',
    appId: '1:520142220218:web:5eaf0059955470d8590b83',
    messagingSenderId: '520142220218',
    projectId: 'ones-3f249',
    authDomain: 'ones-3f249.firebaseapp.com',
    databaseURL: 'https://ones-3f249-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ones-3f249.firebasestorage.app',
    measurementId: 'G-H3X7ZQNPYP',
  );
}
